import Head from "next/head";
import Link from "next/link";
import React, { useContext } from "react";
import { Store } from "../utils/Store";
type Props = {
  children: React.ReactNode;
  title: string;
};
export default function Layout({ title, children }: Props) {
  const { state } = useContext(Store);
  const { cart } = state;
  return (
    <>
      <Head>
        <title>{title ? title + " - Otazon" : "Otazon"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex  items-center m-2 justify-between h-12 shadow-sm ">
            <Link href="/" className="text-lg font-bold">
              Otazon
            </Link>
            <div className="flex gap-3  font-semibold">
              <Link href="/cart">
                Cart
                {cart.cartItems.length > 0 && (
                  <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cart.cartItems.reduce((a: number, c: any) => a + c.qty, 0)}
                  </span>
                )}
              </Link>
              <Link href="/login">Login</Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4 ">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p> Othmane ait taleb © 2023</p>
        </footer>
      </div>
    </>
  );
}
